# Generated by Django 4.1.1 on 2022-12-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(max_length=50, verbose_name="Жанр")),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанрлар",
            },
        ),
        migrations.AlterModelOptions(
            name="text",
            options={"verbose_name": "Мәтін", "verbose_name_plural": "Мәтін"},
        ),
        migrations.AddField(
            model_name="text",
            name="author",
            field=models.CharField(blank=True, max_length=50, verbose_name="Автор"),
        ),
        migrations.AddField(
            model_name="text",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Мәтін атауы"
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="text",
            field=models.TextField(verbose_name="Мәтін"),
        ),
        migrations.AddField(
            model_name="text",
            name="themes",
            field=models.ManyToManyField(
                blank=True, to="words.theme", verbose_name="Жанр"
            ),
        ),
    ]
